/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimoniRouteImport } from './routes/testimoni'
import { Route as SyaratKetentuanRouteImport } from './routes/syarat-ketentuan'
import { Route as SertifikasiRouteImport } from './routes/sertifikasi'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as MitraRouteImport } from './routes/mitra'
import { Route as MetodeRouteImport } from './routes/metode'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as KebijakanPrivasiRouteImport } from './routes/kebijakan-privasi'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventRouteImport } from './routes/event'
import { Route as CaraDaftarRouteImport } from './routes/cara-daftar'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProgramsRouteRouteImport } from './routes/programs/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProgramsSlugRouteImport } from './routes/programs/$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSiteConfigRouteImport } from './routes/admin/site-config'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminTestimonialsIndexRouteImport } from './routes/admin/testimonials/index'
import { Route as AdminResourcesIndexRouteImport } from './routes/admin/resources/index'
import { Route as AdminPromosIndexRouteImport } from './routes/admin/promos/index'
import { Route as AdminGalleryIndexRouteImport } from './routes/admin/gallery/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminContactsIndexRouteImport } from './routes/admin/contacts/index'
import { Route as AdminAlumniIndexRouteImport } from './routes/admin/alumni/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminTestimonialsIdRouteImport } from './routes/admin/testimonials/$id'
import { Route as AdminResourcesIdRouteImport } from './routes/admin/resources/$id'
import { Route as AdminPromosIdRouteImport } from './routes/admin/promos/$id'
import { Route as AdminEventsIdRouteImport } from './routes/admin/events/$id'
import { Route as AdminAlumniIdRouteImport } from './routes/admin/alumni/$id'

const TestimoniRoute = TestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratKetentuanRoute = SyaratKetentuanRouteImport.update({
  id: '/syarat-ketentuan',
  path: '/syarat-ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const SertifikasiRoute = SertifikasiRouteImport.update({
  id: '/sertifikasi',
  path: '/sertifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const MitraRoute = MitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodeRoute = MetodeRouteImport.update({
  id: '/metode',
  path: '/metode',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const KebijakanPrivasiRoute = KebijakanPrivasiRouteImport.update({
  id: '/kebijakan-privasi',
  path: '/kebijakan-privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const CaraDaftarRoute = CaraDaftarRouteImport.update({
  id: '/cara-daftar',
  path: '/cara-daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRouteRoute = ProgramsRouteRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSiteConfigRoute = AdminSiteConfigRouteImport.update({
  id: '/site-config',
  path: '/site-config',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTestimonialsIndexRoute = AdminTestimonialsIndexRouteImport.update({
  id: '/testimonials/',
  path: '/testimonials/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResourcesIndexRoute = AdminResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPromosIndexRoute = AdminPromosIndexRouteImport.update({
  id: '/promos/',
  path: '/promos/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryIndexRoute = AdminGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactsIndexRoute = AdminContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAlumniIndexRoute = AdminAlumniIndexRouteImport.update({
  id: '/alumni/',
  path: '/alumni/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsIdRoute = AdminTestimonialsIdRouteImport.update({
  id: '/testimonials/$id',
  path: '/testimonials/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResourcesIdRoute = AdminResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPromosIdRoute = AdminPromosIdRouteImport.update({
  id: '/promos/$id',
  path: '/promos/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAlumniIdRoute = AdminAlumniIdRouteImport.update({
  id: '/alumni/$id',
  path: '/alumni/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/programs': typeof ProgramsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/alumni': typeof AlumniRoute
  '/cara-daftar': typeof CaraDaftarRoute
  '/event': typeof EventRoute
  '/faq': typeof FaqRoute
  '/founder': typeof FounderRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/metode': typeof MetodeRoute
  '/mitra': typeof MitraRoute
  '/promo': typeof PromoRoute
  '/resources': typeof ResourcesRoute
  '/sertifikasi': typeof SertifikasiRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/testimoni': typeof TestimoniRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-config': typeof AdminSiteConfigRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/admin/alumni/$id': typeof AdminAlumniIdRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/promos/$id': typeof AdminPromosIdRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/alumni/': typeof AdminAlumniIndexRoute
  '/admin/contacts/': typeof AdminContactsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/promos/': typeof AdminPromosIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alumni': typeof AlumniRoute
  '/cara-daftar': typeof CaraDaftarRoute
  '/event': typeof EventRoute
  '/faq': typeof FaqRoute
  '/founder': typeof FounderRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/metode': typeof MetodeRoute
  '/mitra': typeof MitraRoute
  '/promo': typeof PromoRoute
  '/resources': typeof ResourcesRoute
  '/sertifikasi': typeof SertifikasiRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/testimoni': typeof TestimoniRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-config': typeof AdminSiteConfigRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/admin/alumni/$id': typeof AdminAlumniIdRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/promos/$id': typeof AdminPromosIdRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/alumni': typeof AdminAlumniIndexRoute
  '/admin/contacts': typeof AdminContactsIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/gallery': typeof AdminGalleryIndexRoute
  '/admin/promos': typeof AdminPromosIndexRoute
  '/admin/resources': typeof AdminResourcesIndexRoute
  '/admin/testimonials': typeof AdminTestimonialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/programs': typeof ProgramsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/alumni': typeof AlumniRoute
  '/cara-daftar': typeof CaraDaftarRoute
  '/event': typeof EventRoute
  '/faq': typeof FaqRoute
  '/founder': typeof FounderRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/metode': typeof MetodeRoute
  '/mitra': typeof MitraRoute
  '/promo': typeof PromoRoute
  '/resources': typeof ResourcesRoute
  '/sertifikasi': typeof SertifikasiRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/testimoni': typeof TestimoniRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-config': typeof AdminSiteConfigRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/admin/alumni/$id': typeof AdminAlumniIdRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/promos/$id': typeof AdminPromosIdRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/alumni/': typeof AdminAlumniIndexRoute
  '/admin/contacts/': typeof AdminContactsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/promos/': typeof AdminPromosIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/programs'
    | '/about'
    | '/alumni'
    | '/cara-daftar'
    | '/event'
    | '/faq'
    | '/founder'
    | '/galeri'
    | '/jadwal'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/metode'
    | '/mitra'
    | '/promo'
    | '/resources'
    | '/sertifikasi'
    | '/syarat-ketentuan'
    | '/testimoni'
    | '/admin/activity'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/site-config'
    | '/admin/users'
    | '/api/chat'
    | '/programs/$slug'
    | '/admin/'
    | '/programs/'
    | '/admin/alumni/$id'
    | '/admin/events/$id'
    | '/admin/promos/$id'
    | '/admin/resources/$id'
    | '/admin/testimonials/$id'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/alumni/'
    | '/admin/contacts/'
    | '/admin/events/'
    | '/admin/gallery/'
    | '/admin/promos/'
    | '/admin/resources/'
    | '/admin/testimonials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alumni'
    | '/cara-daftar'
    | '/event'
    | '/faq'
    | '/founder'
    | '/galeri'
    | '/jadwal'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/metode'
    | '/mitra'
    | '/promo'
    | '/resources'
    | '/sertifikasi'
    | '/syarat-ketentuan'
    | '/testimoni'
    | '/admin/activity'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/site-config'
    | '/admin/users'
    | '/api/chat'
    | '/programs/$slug'
    | '/admin'
    | '/programs'
    | '/admin/alumni/$id'
    | '/admin/events/$id'
    | '/admin/promos/$id'
    | '/admin/resources/$id'
    | '/admin/testimonials/$id'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/alumni'
    | '/admin/contacts'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/promos'
    | '/admin/resources'
    | '/admin/testimonials'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/programs'
    | '/about'
    | '/alumni'
    | '/cara-daftar'
    | '/event'
    | '/faq'
    | '/founder'
    | '/galeri'
    | '/jadwal'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/metode'
    | '/mitra'
    | '/promo'
    | '/resources'
    | '/sertifikasi'
    | '/syarat-ketentuan'
    | '/testimoni'
    | '/admin/activity'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/site-config'
    | '/admin/users'
    | '/api/chat'
    | '/programs/$slug'
    | '/admin/'
    | '/programs/'
    | '/admin/alumni/$id'
    | '/admin/events/$id'
    | '/admin/promos/$id'
    | '/admin/resources/$id'
    | '/admin/testimonials/$id'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/alumni/'
    | '/admin/contacts/'
    | '/admin/events/'
    | '/admin/gallery/'
    | '/admin/promos/'
    | '/admin/resources/'
    | '/admin/testimonials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ProgramsRouteRoute: typeof ProgramsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AlumniRoute: typeof AlumniRoute
  CaraDaftarRoute: typeof CaraDaftarRoute
  EventRoute: typeof EventRoute
  FaqRoute: typeof FaqRoute
  FounderRoute: typeof FounderRoute
  GaleriRoute: typeof GaleriRoute
  JadwalRoute: typeof JadwalRoute
  KebijakanPrivasiRoute: typeof KebijakanPrivasiRoute
  KontakRoute: typeof KontakRoute
  MetodeRoute: typeof MetodeRoute
  MitraRoute: typeof MitraRoute
  PromoRoute: typeof PromoRoute
  ResourcesRoute: typeof ResourcesRoute
  SertifikasiRoute: typeof SertifikasiRoute
  SyaratKetentuanRoute: typeof SyaratKetentuanRoute
  TestimoniRoute: typeof TestimoniRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimoni': {
      id: '/testimoni'
      path: '/testimoni'
      fullPath: '/testimoni'
      preLoaderRoute: typeof TestimoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat-ketentuan': {
      id: '/syarat-ketentuan'
      path: '/syarat-ketentuan'
      fullPath: '/syarat-ketentuan'
      preLoaderRoute: typeof SyaratKetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sertifikasi': {
      id: '/sertifikasi'
      path: '/sertifikasi'
      fullPath: '/sertifikasi'
      preLoaderRoute: typeof SertifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitra': {
      id: '/mitra'
      path: '/mitra'
      fullPath: '/mitra'
      preLoaderRoute: typeof MitraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metode': {
      id: '/metode'
      path: '/metode'
      fullPath: '/metode'
      preLoaderRoute: typeof MetodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kebijakan-privasi': {
      id: '/kebijakan-privasi'
      path: '/kebijakan-privasi'
      fullPath: '/kebijakan-privasi'
      preLoaderRoute: typeof KebijakanPrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cara-daftar': {
      id: '/cara-daftar'
      path: '/cara-daftar'
      fullPath: '/cara-daftar'
      preLoaderRoute: typeof CaraDaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/site-config': {
      id: '/admin/site-config'
      path: '/site-config'
      fullPath: '/admin/site-config'
      preLoaderRoute: typeof AdminSiteConfigRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/testimonials/': {
      id: '/admin/testimonials/'
      path: '/testimonials'
      fullPath: '/admin/testimonials/'
      preLoaderRoute: typeof AdminTestimonialsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/resources/': {
      id: '/admin/resources/'
      path: '/resources'
      fullPath: '/admin/resources/'
      preLoaderRoute: typeof AdminResourcesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/promos/': {
      id: '/admin/promos/'
      path: '/promos'
      fullPath: '/admin/promos/'
      preLoaderRoute: typeof AdminPromosIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery/': {
      id: '/admin/gallery/'
      path: '/gallery'
      fullPath: '/admin/gallery/'
      preLoaderRoute: typeof AdminGalleryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contacts/': {
      id: '/admin/contacts/'
      path: '/contacts'
      fullPath: '/admin/contacts/'
      preLoaderRoute: typeof AdminContactsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/alumni/': {
      id: '/admin/alumni/'
      path: '/alumni'
      fullPath: '/admin/alumni/'
      preLoaderRoute: typeof AdminAlumniIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials/$id': {
      id: '/admin/testimonials/$id'
      path: '/testimonials/$id'
      fullPath: '/admin/testimonials/$id'
      preLoaderRoute: typeof AdminTestimonialsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/resources/$id': {
      id: '/admin/resources/$id'
      path: '/resources/$id'
      fullPath: '/admin/resources/$id'
      preLoaderRoute: typeof AdminResourcesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/promos/$id': {
      id: '/admin/promos/$id'
      path: '/promos/$id'
      fullPath: '/admin/promos/$id'
      preLoaderRoute: typeof AdminPromosIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/$id': {
      id: '/admin/events/$id'
      path: '/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/alumni/$id': {
      id: '/admin/alumni/$id'
      path: '/alumni/$id'
      fullPath: '/admin/alumni/$id'
      preLoaderRoute: typeof AdminAlumniIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteConfigRoute: typeof AdminSiteConfigRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlumniIdRoute: typeof AdminAlumniIdRoute
  AdminEventsIdRoute: typeof AdminEventsIdRoute
  AdminPromosIdRoute: typeof AdminPromosIdRoute
  AdminResourcesIdRoute: typeof AdminResourcesIdRoute
  AdminTestimonialsIdRoute: typeof AdminTestimonialsIdRoute
  AdminAlumniIndexRoute: typeof AdminAlumniIndexRoute
  AdminContactsIndexRoute: typeof AdminContactsIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminGalleryIndexRoute: typeof AdminGalleryIndexRoute
  AdminPromosIndexRoute: typeof AdminPromosIndexRoute
  AdminResourcesIndexRoute: typeof AdminResourcesIndexRoute
  AdminTestimonialsIndexRoute: typeof AdminTestimonialsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteConfigRoute: AdminSiteConfigRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAlumniIdRoute: AdminAlumniIdRoute,
  AdminEventsIdRoute: AdminEventsIdRoute,
  AdminPromosIdRoute: AdminPromosIdRoute,
  AdminResourcesIdRoute: AdminResourcesIdRoute,
  AdminTestimonialsIdRoute: AdminTestimonialsIdRoute,
  AdminAlumniIndexRoute: AdminAlumniIndexRoute,
  AdminContactsIndexRoute: AdminContactsIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminGalleryIndexRoute: AdminGalleryIndexRoute,
  AdminPromosIndexRoute: AdminPromosIndexRoute,
  AdminResourcesIndexRoute: AdminResourcesIndexRoute,
  AdminTestimonialsIndexRoute: AdminTestimonialsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ProgramsRouteRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteRouteChildren: ProgramsRouteRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteRouteWithChildren = ProgramsRouteRoute._addFileChildren(
  ProgramsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ProgramsRouteRoute: ProgramsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AlumniRoute: AlumniRoute,
  CaraDaftarRoute: CaraDaftarRoute,
  EventRoute: EventRoute,
  FaqRoute: FaqRoute,
  FounderRoute: FounderRoute,
  GaleriRoute: GaleriRoute,
  JadwalRoute: JadwalRoute,
  KebijakanPrivasiRoute: KebijakanPrivasiRoute,
  KontakRoute: KontakRoute,
  MetodeRoute: MetodeRoute,
  MitraRoute: MitraRoute,
  PromoRoute: PromoRoute,
  ResourcesRoute: ResourcesRoute,
  SertifikasiRoute: SertifikasiRoute,
  SyaratKetentuanRoute: SyaratKetentuanRoute,
  TestimoniRoute: TestimoniRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
